name: Build Uptime

on:
  schedule:
    - cron: "*/30 * * * *"
  issues:
    types: [edited, closed, deleted, labeled]
  workflow_dispatch:

permissions: write-all

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  website:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Update Announcement
        if: ${{ github.event.issue && github.event.issue.user.login == 'Prince527GitHub' }}
        run: bun announce.js

      - name: Update Status
        if: ${{ github.event_name != 'issues' }}
        run: bun update.js
        env:
          DISCORD: ${{ vars.DISCORD }}

      - name: Check for changes
        id: changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name actions[bot]
          git config user.email actions@serversmp.xyz
          git commit -m "Update Uptime"
          git push

      - name: Create Artifact
        if: steps.changes.outputs.changed == 'true'
        uses: actions/upload-pages-artifact@v4
        with:
          name: website
          path: ./src/

      - name: Setup Pages
        if: steps.changes.outputs.changed == 'true'
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        if: steps.changes.outputs.changed == 'true'
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: website
